name: Taxpayer-calls
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy<=1.26
  - pandas<=2.10
  - matplotlib<=3.8
  - seaborn<=0.12.2
  - scikit-learn<=1.3
  - haversine<=2.5
  - jupyter
  - pip
  - pip:
    - faker==27.0.0
    - fastapi==0.111.1
    - pydantic==2.0.3
    - uvicorn==0.30.6
